[package]
name = "google-secretmanager1"
version = "0.1.0-20210319"
authors = ["Glenn Griffin <ggriffiniii@gmail.com"]
edition = "2018"
# for now, let's not even accidentally publish these
publish = false

[features]
default = ["rustls-tls"]

native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
google_api_auth = { git = "https://github.com/bes/generator", branch = "refactor/async" }
google_field_selector = { git = "https://github.com/bes/generator", branch = "refactor/async" }
mime = "0.3"
percent-encoding = "2"
reqwest = { version = "0.11.2", default-features = false, features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
textnonce = "0.6"

[dependencies.google_api_bytes]
git = "https://github.com/bes/generator"
